query Event($id: Int!) {
  event(id: $id) {
    id
    title
    date

    topics {
      id
      title
      speaker
      speakerPhoto
      slides
      video
    }

    photos {
      id
      link
    }
  }
}
